#!/usr/bin/env bash
# generate-stats.sh — categories/*.md 분석 → README의 STATS 섹션 자동 갱신
#
# 산출:
#   - 카테고리별 스킬 수 (Top 10 mermaid pie)
#   - 도구별 호환성 (CC/GC/CX/CP/OC/CR/WS 등장 빈도)
#   - 언어 분포 (한국어 / 영+한 / 다국어(KO))
#   - 총합 통계 박스
#
# Idempotent: README의 <!-- STATS:START --> ~ <!-- STATS:END --> 마커 사이 영역 교체.
# 마커 없으면 '## 최근 업데이트' 섹션 위에 신규 삽입.
#
# macOS bash 3.2 호환을 위해 associative array 사용 안 함.
set -eo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CATEGORIES_DIR="$ROOT/categories"
README="$ROOT/README.md"
STATS_TMP="$(mktemp)"

# ── 카테고리 한글 라벨 (case 기반) ─────────────────────────────────────────
label_of() {
  case "$1" in
    ai-prompt)        echo "AI & 프롬프트 엔지니어링" ;;
    backend)          echo "백엔드" ;;
    code-review)      echo "코드 리뷰" ;;
    collections)      echo "종합 스킬 컬렉션" ;;
    communication)    echo "커뮤니케이션" ;;
    content-media)    echo "콘텐츠 & 미디어" ;;
    debugging)        echo "디버깅 & 빌드 에러" ;;
    devops)           echo "DevOps & 배포" ;;
    documentation)    echo "문서화" ;;
    frameworks)       echo "프레임워크" ;;
    game-dev)         echo "게임 개발" ;;
    git-workflow)     echo "Git & 워크플로우" ;;
    guides)           echo "가이드 & 튜토리얼" ;;
    korean-services)  echo "한국 생활 서비스" ;;
    korean-writing)   echo "글쓰기 & 한국어" ;;
    multi-agent)      echo "멀티에이전트" ;;
    office-docs)      echo "오피스 & 문서" ;;
    performance)      echo "성능 최적화" ;;
    project-init)     echo "프로젝트 초기화" ;;
    refactoring)      echo "리팩토링" ;;
    research-web)     echo "리서치 & 웹" ;;
    security)         echo "보안 감사" ;;
    testing)          echo "테스트 & TDD" ;;
    utilities)        echo "유틸리티 도구" ;;
    web-frontend)     echo "웹 프론트엔드" ;;
    *)                echo "$1" ;;
  esac
}

# ── 헬퍼: 한 파일의 데이터 행 카운트 ───────────────────────────────────────
count_rows() {
  local file="$1"
  [[ -f "$file" ]] || { echo 0; return; }
  grep "^|" "$file" 2>/dev/null \
    | grep -v "^|[-: |]*|$" \
    | grep -vE "^\| *(이름|레포|Name|Repo|스킬|카테고리|Category|Icon|Source|Label|아이콘|출처|도구|Tool|Skill)[[:space:]]*\|" \
    | wc -l \
    | tr -d ' '
}

# ── 1. 모든 카테고리 행 한 파일에 합치기 + 카테고리별 카운트 산출 ──────────
TMP_ROWS="$(mktemp)"
CATS_FILE="$(mktemp)"
total_skills=0
n_categories=0

for file in "$CATEGORIES_DIR"/*.md; do
  [[ -f "$file" ]] || continue
  name="$(basename "$file" .md)"
  n="$(count_rows "$file")"
  echo "${n} ${name}" >> "$CATS_FILE"
  total_skills=$((total_skills + n))
  n_categories=$((n_categories + 1))

  grep "^|" "$file" 2>/dev/null \
    | grep -v "^|[-: |]*|$" \
    | grep -vE "^\| *(이름|레포|Name|Repo|스킬|카테고리|Category|Icon|Source|Label|아이콘|출처|도구|Tool|Skill)[[:space:]]*\|" \
    >> "$TMP_ROWS" || true
done

# ── 2. 도구 분포 (도구 컬럼 = 3번째 컬럼: |name|tools|...) ──────────────────
count_tool() {
  local tool="$1"
  awk -F'|' -v t="$tool" '{
    gsub(/ /, "", $3)
    split($3, arr, /\//)
    for (i in arr) if (arr[i] == t) { c++ ; next }
  } END { print c+0 }' "$TMP_ROWS"
}

# ── 3. 언어 분포 ───────────────────────────────────────────────────────────
KO_PURE="$(awk -F'|' '$6 ~ /^[[:space:]]*한국어[[:space:]]*$/ {print}' "$TMP_ROWS" 2>/dev/null | wc -l | tr -d ' ')"
KO_PLUS_EN="$(awk -F'|' '$6 ~ /영\+한/ {print}' "$TMP_ROWS" 2>/dev/null | wc -l | tr -d ' ')"
KO_MULTI="$(awk -F'|' '$6 ~ /다국어\(KO\)/ {print}' "$TMP_ROWS" 2>/dev/null | wc -l | tr -d ' ')"

# ── 4. 등록 레포 수 ────────────────────────────────────────────────────────
known_count=0
if [[ -f "$ROOT/data/known-repos.json" ]] && command -v jq &>/dev/null; then
  known_count="$(jq '.repos | length' "$ROOT/data/known-repos.json")"
fi

# ── 5. STATS 블록 빌드 ─────────────────────────────────────────────────────
{
  echo '<!-- STATS:START — auto-generated by .github/scripts/generate-stats.sh -->'
  echo ''
  echo '## 📊 통계 한눈에'
  echo ''
  TODAY="$(date -u +%Y-%m-%d)"
  echo "<sub>마지막 갱신: ${TODAY} · 자동 생성 · 데이터는 [categories/](categories/) 표에서 직접 카운트</sub>"
  echo ''
  echo '<table>'
  echo '<tr align="center">'
  echo "<td>📦 <b>총 스킬·에이전트</b><br/><sub>카테고리 표 행 합산</sub></td>"
  echo "<td>🗂️ <b>등록 레포</b><br/><sub>known-repos.json</sub></td>"
  echo "<td>🏷️ <b>활성 카테고리</b><br/><sub>categories/*.md</sub></td>"
  echo '</tr>'
  echo '<tr align="center">'
  echo "<td><h2>${total_skills}+</h2></td>"
  echo "<td><h2>${known_count}</h2></td>"
  echo "<td><h2>${n_categories}</h2></td>"
  echo '</tr>'
  echo '</table>'
  echo ''
  echo '### 카테고리별 분포 (Top 10)'
  echo ''
  echo '```mermaid'
  echo 'pie showData'
  echo '    title 카테고리별 스킬 수'

  # 카운트 desc 정렬 → top 10 (개수>0인 것만)
  sort -rn "$CATS_FILE" | head -10 | while read -r cnt name; do
    [[ "$cnt" -gt 0 ]] || continue
    label="$(label_of "$name")"
    echo "    \"${label}\" : ${cnt}"
  done
  echo '```'
  echo ''
  echo '### 도구별 호환성 등장 빈도'
  echo ''
  echo '```mermaid'
  echo 'pie showData'
  echo '    title 도구별 행 등장 횟수'
  for tool in CC GC CX CP OC CR WS; do
    cnt="$(count_tool "$tool")"
    [[ "$cnt" -gt 0 ]] && echo "    \"${tool}\" : ${cnt}"
  done
  echo '```'
  echo ''
  echo '### 언어 분포'
  echo ''
  echo '```mermaid'
  echo 'pie showData'
  echo '    title 한국어 호환성'
  [[ "$KO_PURE" -gt 0 ]] && echo "    \"한국어\" : ${KO_PURE}"
  [[ "$KO_PLUS_EN" -gt 0 ]] && echo "    \"영+한\" : ${KO_PLUS_EN}"
  [[ "$KO_MULTI" -gt 0 ]] && echo "    \"다국어(KO)\" : ${KO_MULTI}"
  echo '```'
  echo ''
  echo '<!-- STATS:END -->'
} > "$STATS_TMP"

# ── 6. README 적용 ─────────────────────────────────────────────────────────
if grep -q '<!-- STATS:START' "$README"; then
  awk -v stats_file="$STATS_TMP" '
    /<!-- STATS:START/ { in_block=1; while ((getline line < stats_file) > 0) print line; close(stats_file); next }
    /<!-- STATS:END/   { in_block=0; next }
    !in_block { print }
  ' "$README" > "${README}.new" && mv "${README}.new" "$README"
  echo "[generate-stats] STATS 마커 영역 교체"
elif grep -q '^## 최근 업데이트' "$README"; then
  awk -v stats_file="$STATS_TMP" '
    /^## 최근 업데이트/ && !inserted {
      while ((getline line < stats_file) > 0) print line
      close(stats_file)
      print ""
      print "---"
      print ""
      inserted=1
    }
    { print }
  ' "$README" > "${README}.new" && mv "${README}.new" "$README"
  echo "[generate-stats] STATS 마커 신규 삽입 (최근 업데이트 위)"
else
  {
    echo ''
    echo '---'
    echo ''
    cat "$STATS_TMP"
  } >> "$README"
  echo "[generate-stats] STATS 마커 파일 끝 추가"
fi

rm -f "$STATS_TMP" "$TMP_ROWS" "$CATS_FILE"
echo "[generate-stats] 완료. total_skills=${total_skills}, known_repos=${known_count}, categories=${n_categories}"
