#!/usr/bin/env bash
# generate-digest.sh — 지난 N일 자동화 활동 요약을 README의 DIGEST 마커 사이에 삽입
#
# DAYS_BACK 환경변수로 윈도 조절 (default: 1 = 어제 자정 이후 ~ 지금)
#
# 추출 정보:
#   - skill-scout 머지 commit 수 + 신규 스킬 합계
#   - link-checker 머지 commit 수 + 제거된 죽은 링크 합계
#   - sync-counts 머지 commit 수
#   - weekly-picks 머지 commit 수
#   - mermaid pie + 최근 7일 timeline 표
set -eo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
README="$ROOT/README.md"
DAYS_BACK="${DAYS_BACK:-7}"

# GNU date / BSD date 양쪽 호환
SINCE="$(date -u -d "${DAYS_BACK} days ago" '+%Y-%m-%dT00:00:00Z' 2>/dev/null \
  || date -u -v-${DAYS_BACK}d '+%Y-%m-%dT00:00:00Z')"

cd "$ROOT"

# ── git log 기반 자동 commit 분류 ─────────────────────────────────────────
N_SKILL_SCOUT="$(git log --since="$SINCE" --grep="신규 스킬" --oneline 2>/dev/null | wc -l | tr -d ' ')"
N_LINK_CHECK="$(git log --since="$SINCE" --grep="죽은 링크"  --oneline 2>/dev/null | wc -l | tr -d ' ')"
N_SYNC="$(git log --since="$SINCE" --grep="카테고리 카운트" --oneline 2>/dev/null | wc -l | tr -d ' ')"
N_PICKS="$(git log --since="$SINCE" --grep="이 주의 스킬"   --oneline 2>/dev/null | wc -l | tr -d ' ')"

# 변동 합계 (commit 메시지에서 "N개" 패턴 추출)
# awk 단일 파이프로 처리 — grep 결과가 비어있어도 pipefail에 안 걸림
TOTAL_NEW_SKILLS="$(git log --since="$SINCE" --grep="신규 스킬" --oneline 2>/dev/null \
  | awk '{ while (match($0, /[0-9]+개/)) { s += substr($0, RSTART, RLENGTH-1) + 0; $0 = substr($0, RSTART+RLENGTH) } } END {print s+0}')"
TOTAL_DEAD_REMOVED="$(git log --since="$SINCE" --grep="죽은 링크" --oneline 2>/dev/null \
  | awk '{ while (match($0, /[0-9]+개/)) { s += substr($0, RSTART, RLENGTH-1) + 0; $0 = substr($0, RSTART+RLENGTH) } } END {print s+0}')"

TODAY="$(date -u +%Y-%m-%d)"

# ── 일자별 timeline 표 (최근 7일, ISO 날짜) ───────────────────────────────
DAILY_TMP="$(mktemp)"
for i in $(seq 6 -1 0); do
  d="$(date -u -d "${i} days ago" '+%Y-%m-%d' 2>/dev/null || date -u -v-${i}d '+%Y-%m-%d')"
  # 그 날 commit 카운트
  c_ss="$(git log --since="${d}T00:00:00Z" --until="${d}T23:59:59Z" --grep="신규 스킬" --oneline 2>/dev/null | wc -l | tr -d ' ')"
  c_lc="$(git log --since="${d}T00:00:00Z" --until="${d}T23:59:59Z" --grep="죽은 링크"  --oneline 2>/dev/null | wc -l | tr -d ' ')"
  c_sc="$(git log --since="${d}T00:00:00Z" --until="${d}T23:59:59Z" --grep="카테고리 카운트" --oneline 2>/dev/null | wc -l | tr -d ' ')"
  c_wp="$(git log --since="${d}T00:00:00Z" --until="${d}T23:59:59Z" --grep="이 주의 스킬"   --oneline 2>/dev/null | wc -l | tr -d ' ')"
  echo "${d}|${c_ss}|${c_lc}|${c_sc}|${c_wp}" >> "$DAILY_TMP"
done

# ── DIGEST 블록 빌드 ──────────────────────────────────────────────────────
DIGEST_TMP="$(mktemp)"
{
  echo "<!-- DIGEST:START — auto-generated by .github/scripts/generate-digest.sh -->"
  echo ""
  echo "## 🤖 최근 자동화 활동"
  echo ""
  echo "<sub>지난 ${DAYS_BACK}일 (since ${SINCE} UTC) · 자동 생성 · 마지막 갱신 ${TODAY}</sub>"
  echo ""
  echo '<table>'
  echo '<tr align="center">'
  echo "<td>🔍 <b>skill-scout</b><br/><sub>신규 스킬 발견</sub></td>"
  echo "<td>🔗 <b>link-checker</b><br/><sub>죽은 링크 제거</sub></td>"
  echo "<td>📊 <b>sync-counts</b><br/><sub>카운트·통계 갱신</sub></td>"
  echo "<td>⭐ <b>weekly-picks</b><br/><sub>이 주의 스킬</sub></td>"
  echo '</tr>'
  echo '<tr align="center">'
  echo "<td><b>${N_SKILL_SCOUT}</b> run · <b>+${TOTAL_NEW_SKILLS}</b> 스킬</td>"
  echo "<td><b>${N_LINK_CHECK}</b> run · <b>-${TOTAL_DEAD_REMOVED}</b> dead link</td>"
  echo "<td><b>${N_SYNC}</b> run</td>"
  echo "<td><b>${N_PICKS}</b> run</td>"
  echo '</tr>'
  echo '</table>'
  echo ""
  echo "### 일자별 활동 (최근 7일)"
  echo ""
  echo "| 날짜 | 🔍 신규 | 🔗 정리 | 📊 동기화 | ⭐ 추천 |"
  echo "|------|:---:|:---:|:---:|:---:|"
  while IFS='|' read -r d c_ss c_lc c_sc c_wp; do
    # 0인 칸은 dot 표시
    f_ss="$([ "$c_ss" -gt 0 ] && echo "**$c_ss**" || echo "·")"
    f_lc="$([ "$c_lc" -gt 0 ] && echo "**$c_lc**" || echo "·")"
    f_sc="$([ "$c_sc" -gt 0 ] && echo "**$c_sc**" || echo "·")"
    f_wp="$([ "$c_wp" -gt 0 ] && echo "**$c_wp**" || echo "·")"
    echo "| ${d} | ${f_ss} | ${f_lc} | ${f_sc} | ${f_wp} |"
  done < "$DAILY_TMP"
  echo ""
  echo "<sub>전체 PR 이력: [Actions](https://github.com/J-nowcow/awesome-korean-agent-skills/actions)</sub>"
  echo ""
  echo "<!-- DIGEST:END -->"
} > "$DIGEST_TMP"

# ── README 삽입 (STATS 블록 뒤, 최근 업데이트 앞) ─────────────────────────
if grep -q '<!-- DIGEST:START' "$README"; then
  awk -v dfile="$DIGEST_TMP" '
    /<!-- DIGEST:START/ { in_block=1; while ((getline line < dfile) > 0) print line; close(dfile); next }
    /<!-- DIGEST:END/   { in_block=0; next }
    !in_block { print }
  ' "$README" > "${README}.new" && mv "${README}.new" "$README"
  echo "[generate-digest] DIGEST 마커 교체"
elif grep -q '<!-- STATS:END' "$README"; then
  # STATS 블록 바로 뒤에 삽입
  awk -v dfile="$DIGEST_TMP" '
    /<!-- STATS:END/ && !inserted {
      print
      print ""
      print "---"
      print ""
      while ((getline line < dfile) > 0) print line
      close(dfile)
      inserted=1; next
    }
    { print }
  ' "$README" > "${README}.new" && mv "${README}.new" "$README"
  echo "[generate-digest] DIGEST 마커 신규 삽입 (STATS:END 뒤)"
else
  echo "[generate-digest] 삽입 위치 못 찾음 (STATS 블록 없음) — skip"
  rm -f "$DIGEST_TMP" "$DAILY_TMP"
  exit 0
fi

rm -f "$DIGEST_TMP" "$DAILY_TMP"
echo "[generate-digest] 완료. skill-scout=${N_SKILL_SCOUT} (+${TOTAL_NEW_SKILLS}), link-checker=${N_LINK_CHECK} (-${TOTAL_DEAD_REMOVED}), sync=${N_SYNC}, picks=${N_PICKS}"
